name: app_aman
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.8
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0 
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_database: ^11.1.4
  fl_chart: ^0.69.0
  intl: ^0.19.0
  syncfusion_flutter_gauges: ^27.1.56
  syncfusion_flutter_charts: ^27.1.56
  image_picker: ^1.1.2
  encrypt: ^5.0.0
  url_launcher: ^6.0.9
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  onesignal_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "assets/1024.png"
  ios: true
  image_path: "assets/1024.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true  # Pastikan ini disetel ke true untuk menggunakan Material Icons
  assets:
    - assets/bg1.png  
    - assets/bg2.png
    - assets/Aman .PNG
    - assets/dapur.jpg
    - assets/smart home oke.jpg  
    - assets/bg gas.jpg
    - assets/bg.jpg
    - assets/8.png
    - assets/Frame 3.png
    - assets/default_profil.png
    - assets/chart_line.png
    - assets/Vector.png
    - assets/Graph.gif

  fonts:
    - family: HammersmithOne  # Tambahkan font custom jika diperlukan untuk teks
      fonts:
        - asset: assets/hammersmith-one/HammersmithOne.ttf
