// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOufebXZ3NIZO0ivdBs4P1RbI8tyk1yk',
    appId: '1:231568599360:android:a92cd9f5c81a67a20732a5',
    messagingSenderId: '231568599360',
    projectId: 'aman-8a19f',
    storageBucket: 'aman-8a19f.appspot.com',
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSMaxvmcGz8VhTKLLDRU6VtCbaINJ4ZzQ',
    appId: '1:231568599360:ios:50d6e1de1be5a3bc0732a5',
    messagingSenderId: '231568599360',
    projectId: 'aman-8a19f',
    storageBucket: 'aman-8a19f.appspot.com',
    iosBundleId: 'com.zero.aman',
    
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3KNClisZpXmx6p_xoxSI5aVbaFJDGSY',
    appId: '1:231568599360:web:eba26777c72e3f370732a5',
    messagingSenderId: '231568599360',
    projectId: 'aman-8a19f',
    authDomain: 'aman-8a19f.firebaseapp.com',
    storageBucket: 'aman-8a19f.appspot.com',
    measurementId: 'G-RHPPTRKT04',
    databaseURL: 'https://aman-8a19f.firebaseio.com',
  );

}